#!/usr/bin/bash

dest="$HOME/Downloads"

while IFS= read -r -d '' f
do 
  if [[ $(file "$f") =~ ": Bourne-Again shell script" ]]; then
    mv -vn "$f" "$dest/scripts"
  elif [[ $(file "$f") =~ ": ASCII text" ]]; then
    mv -vn "$f" "$dest/documents"
  fi
done < <(find . -maxdepth 1 -not -path '*/.*' -not -name '.*' -prune -type f -print0)


