#!/bin/bash
###################################################################### 
#Copyright (C) 2019  Kris Occhipinti
#https://filmsbykris.com

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
###################################################################### 

display="xrandr |grep primary|awk '{print $1}'"
jmp=".05"
#display="eDP1"

level="$(xrandr --verbose | grep -i brightness | cut -f2 -d ' ' | head -n1)"


if (( $(echo $level '<' 1|bc -l) )) && [ "$1" = "up" ];then
  level=$(echo "$level + $jmp"|bc) 
elif (( $(echo $level '>' 0|bc -l) ));then
  level=$(echo "$level - $jmp"|bc) 
fi
  
xrandr --output eDP1 --brightness $level
level="$(echo  "$level * 100"|bc|cut -d\. -f1)"
notify-send -t 200 "Brightness" "$level%"
echo "$level%"