#!/bin/bash
###################################################################### 
#Copyright (C) 2019  Kris Occhipinti
#https://filmsbykris.com

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
###################################################################### 

function mount(){
  drive="$((echo "quit";lsblk -nro name,mountpoint | awk '$1~/[[:digit:]]/ && $2 == ""')|fzf)"
  if [ "$drive" != "quit" ];then
    label="$(lsblk -nro name,label,uuid|grep "$drive"|awk '{print $2}')"
    sudo mkdir -p /media/$label
    sudo mount -o umask=000 /dev/$drive /media/$label
  fi
  exit 0
}

function unmount(){
  drive="$((echo "quit";lsblk -nro name,mountpoint | awk '$1~/[[:digit:]]/ && $2 != ""')|fzf)"
  if [ "$drive" != "quit" ];then
    #label="$(lsblk -nro name,label,uuid|grep "$drive"|awk '{print $2}')"
    drive="$(echo $drive|awk '{print $1}')"
    sudo umount /dev/$drive
    #sudo rm /media/$label
  fi
  exit 0
}

if [ "$1" = "u" ];then
  unmount
else
  mount
fi